### ISSUE TITLE
Subscribe problem

### ISSUE THREAD

**Issue by asadkov-hts** [Velorexe/Unity-Android-Bluetooth-Low-Energy#29]
Hi, trying to use your library. 
But can't get the subscribed data.
Here is the sample code:
public void SubscribeService()
    {
        if(!_isSubscribed)
        {
            _subscribeToCharacteristic = new SubscribeToCharacteristic(_deviceUuid, serviceId, readCharacteristicId, OnDataReceive, true);
            BleManager.Instance.QueueCommand(_subscribeToCharacteristic);
            _isSubscribed = true;
        }
    }
Before that, I scan the devices, connect to the one I need. After that, I sign up for a characteristic. 
At the same time, in Android Logcat I can see that data is coming in, but the callback function is never called (OnDataReceive)

**Comment by Velorexe** [comment]
Hi @asadkov-hts 

Interesting, the fact that data is coming in is good, but interesting that it's not passing it to your command. Could be an issue with the `CustomGatt` check in the `SubscribeToCharacteristic.CommandReceived` method. Can you show me one of the debug messages that the Android Logcat puts out? And the UUID's of the Service and Characteristic if you want to share them, helps with the comparison to see what's exactly going wrong.

What I'm interested to see is how the `BleObject` data that the Android Logcat shows compares to the data that you put into the constructor.

**Comment by asadkov-hts** [comment]
Hello @Velorexe.
I had to switch to a paid plugin due to project deadlines. 
But I am interested to help solve this problem, I can test it within a week and provide you with logs. 
What else might be interesting, I was able to get data via "BleMessageReceived UnityOnMessageReceived". By identifying my data through the "CharacteristicValueChanged" command. But there's a problem here too, the data is always 20 bytes in size. In my case it should be 43 bytes. Probably we need a mechanism for MTU size matching.

**Comment by Velorexe** [comment]
Unfortunate to hear that you had to switch, but I understand that you're pressed with deadlines too. Glad you gave this plugin a chance though!

I'm looking forward to hearing about those logs. I'll run some tests as well with custom UUID's and larger byte arrays to see if I can find the same issue.

**Comment by Velorexe** [comment]
Hi @lucapauri ,

Interesting, I haven't taken a deep dive into the MTU size matching at all and since the default of 20 bytes always worked for me, I didn't bother checking it out. I'll take a look at adding an option to change the MTU size or just match the size to the packages being send.

Sorry about the hassle that it may have caused!

**Comment by Velorexe** [comment]
Hi,

This should be fixed in the new v0.0.3-alpha.0 release. Inside the `BleDevice` class there's a method where a new MTU size can be requested with a callback if changing it was done successfully or not.
