### ISSUE TITLE
Permission missing

### ISSUE THREAD

**Issue by lucasmontec-fortis** [Velorexe/Unity-Android-Bluetooth-Low-Energy#37]
Hey! I was testing the implementation and it seems that the provided manifest is missing the bluetooth scan permission:
<uses-permission android:name="android.permission.BLUETOOTH_SCAN"/>

`2024/02/25 20:08:31.653 25093 25117 Error Unity AndroidJavaException: java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for AttributionSource { uid = 10867, packageName = com.sawce.catbotcontroller, attributionTag = null, token = android.os.BinderProxy@cb6860c, next = null }: GattService registerScanner
`

**Comment by Velorexe** [comment]
Good call, I'll add it to the manifest.
