### ISSUE TITLE
Broken path to unity.jar

### ISSUE THREAD

**Issue by nadiDS2** [Velorexe/Unity-Android-Bluetooth-Low-Energy#47]
The path for unity.jar in build.grade:
```    implementation files('F:\\Projects\\UnityAndroidBLE\\app\\libs\\unity.jar')```
is not universal.  it should be 
```    implementation files('libs/unity.jar)'```

**Comment by Velorexe** [comment]
Good point, that's a mistake on my part.
That's changed in the coming update.
