### ISSUE TITLE
BluetoothDevice hasn't been discovered yet error when attempting to connect to a device

### ISSUE THREAD

**Issue by MaxPalmer-UH** [Velorexe/Unity-Android-Bluetooth-Low-Energy#48]
Hi, I'm getting this warning in the android log when I attempt to connect to a device listed after scanning for devices. Why might this be - the scan command looks like it populates the list based on the discovered devices?

"BluetoothDevice hasn't been discovered yet"

Also, if I want to read and write characteristics, should I move from main to the overhaul branch?

**Comment by MaxPalmer-UH** [comment]
Thanks.

**Comment by MaxPalmer-UH** [comment]
Sadly we never got it to be reliable and moved to another solution.

**Comment by Velorexe** [comment]
My apologies for the lack of communication. Understandable that you had to move to a seperate library.
Internally Android needs to register the device before a connection can be made, the error / warning that you're experiencing is because no scan has been executed yet. Closing this issue.
