### ISSUE TITLE
Guide on how to get started?

### ISSUE THREAD

**Issue by skuller314** [Velorexe/Unity-Android-Bluetooth-Low-Energy#63]
I'd like to use test the example scenes and code, but the latest unity package is from march 2023, how do I import the raw files from the GitHub into unity to test it?

**Comment by skuller314** [comment]
Should I use files from main or from the Refactored Branch also?

**Comment by paulhayes** [comment]
Morning, use Unity Package Manager, add the package via git URL. Then while still in the Package Manager, select the samples tab and import the samples.
